# This workflow will do a clean install of node dependencies, tests and extract coverage
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: it-should-skip CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-collector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
      - name: Running Tests
        run: npm t
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
